-- Seed 50 exercises across all 7 categories
-- Source: docs/content/exercise-seed-data.json

INSERT INTO exercises (name, description, category, muscle_groups, difficulty, audio_cues, is_premium) VALUES

-- ═══ Strength (15) ═══
('Push-up', 'Start in a high plank with hands shoulder-width apart. Lower your chest to the ground, keeping elbows at 45 degrees, then push back up to start.', 'strength', ARRAY['chest','triceps','shoulders','core'], 'beginner', '[{"timestamp":0,"text":"Push-ups. Lower your chest to the ground and press back up.","type":"instruction"}]'::jsonb, false),
('Pull-up', 'Hang from a bar with palms facing away, shoulder-width apart. Pull yourself up until your chin clears the bar, then lower with control.', 'strength', ARRAY['back','biceps','forearms'], 'intermediate', '[{"timestamp":0,"text":"Pull-ups. Pull your chin over the bar and lower with control.","type":"instruction"}]'::jsonb, false),
('Barbell Back Squat', 'With a barbell across your upper back, stand feet shoulder-width apart. Sit your hips back and down until thighs are parallel, then drive through your heels to stand.', 'strength', ARRAY['quads','glutes','hamstrings','core'], 'intermediate', '[{"timestamp":0,"text":"Barbell squats. Sit back and down, then drive through your heels.","type":"instruction"}]'::jsonb, false),
('Deadlift', 'Stand with feet hip-width, barbell over mid-foot. Hinge at hips, grip the bar, then drive through your feet to stand tall. Reverse to lower.', 'strength', ARRAY['back','hamstrings','glutes','core','forearms'], 'intermediate', '[{"timestamp":0,"text":"Deadlifts. Hinge at the hips, grip the bar, and stand tall.","type":"instruction"}]'::jsonb, false),
('Overhead Press', 'Stand with a barbell at shoulder height, palms forward. Press the bar straight overhead until arms are locked, then lower to shoulders.', 'strength', ARRAY['shoulders','triceps','core'], 'intermediate', '[{"timestamp":0,"text":"Overhead press. Press the bar straight up and lock out your arms.","type":"instruction"}]'::jsonb, false),
('Dumbbell Bicep Curl', 'Stand holding dumbbells at your sides, palms forward. Curl the weights toward your shoulders, squeezing at the top, then lower slowly.', 'strength', ARRAY['biceps','forearms'], 'beginner', '[{"timestamp":0,"text":"Bicep curls. Curl up, squeeze at the top, and lower slowly.","type":"instruction"}]'::jsonb, false),
('Tricep Dip', 'Support yourself on parallel bars with arms straight. Lower your body by bending elbows to 90 degrees, then press back up.', 'strength', ARRAY['triceps','chest','shoulders'], 'intermediate', '[{"timestamp":0,"text":"Tricep dips. Lower to 90 degrees and press back up.","type":"instruction"}]'::jsonb, false),
('Bent-Over Row', 'Hinge forward at the hips holding a barbell. Pull the bar to your lower chest, squeezing your shoulder blades together, then lower.', 'strength', ARRAY['back','biceps','core'], 'intermediate', '[{"timestamp":0,"text":"Bent-over rows. Pull to your chest and squeeze your shoulder blades.","type":"instruction"}]'::jsonb, false),
('Lunges', 'Step forward with one foot, lowering your back knee toward the ground. Keep your front knee over your ankle, then push back to standing.', 'strength', ARRAY['quads','glutes','hamstrings','core'], 'beginner', '[{"timestamp":0,"text":"Lunges. Step forward and lower your back knee toward the ground.","type":"instruction"}]'::jsonb, false),
('Plank', 'Hold a straight-arm or forearm plank with your body in a straight line from head to heels. Engage your core and breathe steadily.', 'strength', ARRAY['core','shoulders'], 'beginner', '[{"timestamp":0,"text":"Plank hold. Keep your body in a straight line and engage your core.","type":"instruction"}]'::jsonb, false),
('Lateral Raise', 'Stand with dumbbells at your sides. Raise your arms out to the sides until shoulder height, palms facing down, then lower with control.', 'strength', ARRAY['shoulders'], 'beginner', '[{"timestamp":0,"text":"Lateral raises. Lift your arms to the sides and lower with control.","type":"instruction"}]'::jsonb, false),
('Hip Thrust', 'Sit with upper back against a bench, barbell across hips. Drive through your heels to lift hips until body forms a straight line, squeezing glutes at top.', 'strength', ARRAY['glutes','hamstrings','core'], 'intermediate', '[{"timestamp":0,"text":"Hip thrusts. Drive your hips up and squeeze your glutes at the top.","type":"instruction"}]'::jsonb, false),
('Calf Raise', 'Stand on the edge of a step with heels hanging off. Rise up onto your toes as high as possible, then lower your heels below the step.', 'strength', ARRAY['calves'], 'beginner', '[{"timestamp":0,"text":"Calf raises. Rise up on your toes and lower below the step.","type":"instruction"}]'::jsonb, false),
('Russian Twist', 'Sit with knees bent, lean back slightly, and hold a weight. Rotate your torso side to side, touching the weight to the ground on each side.', 'strength', ARRAY['core'], 'beginner', '[{"timestamp":0,"text":"Russian twists. Rotate side to side and touch the weight down.","type":"instruction"}]'::jsonb, false),
('Farmer''s Walk', 'Hold heavy dumbbells or kettlebells at your sides. Walk forward with tall posture, shoulders back, core braced, for the prescribed distance or time.', 'strength', ARRAY['forearms','core','shoulders'], 'beginner', '[{"timestamp":0,"text":"Farmer''s walk. Stand tall, brace your core, and walk forward.","type":"instruction"}]'::jsonb, false),

-- ═══ Cardio (8) ═══
('Running', 'Maintain a steady running pace at a conversational effort. Land with a midfoot strike, keep arms relaxed at 90 degrees, and breathe rhythmically.', 'cardio', ARRAY['quads','hamstrings','calves','core'], 'beginner', '[{"timestamp":0,"text":"Steady-state run. Find your rhythm and keep a conversational pace.","type":"instruction"}]'::jsonb, false),
('Jump Rope', 'Jump with both feet together, rotating the rope with your wrists. Stay on the balls of your feet with soft knees and a slight bounce.', 'cardio', ARRAY['calves','core','shoulders'], 'beginner', '[{"timestamp":0,"text":"Jump rope. Stay light on your feet and rotate from the wrists.","type":"instruction"}]'::jsonb, false),
('Burpee', 'From standing, drop into a squat, kick feet back to plank, do a push-up, jump feet forward, then explosively jump up with arms overhead.', 'cardio', ARRAY['full_body'], 'intermediate', '[{"timestamp":0,"text":"Burpees. Drop down, push-up, jump up. Keep moving.","type":"instruction"}]'::jsonb, false),
('Mountain Climbers', 'Start in a plank position. Drive one knee toward your chest, then quickly switch legs in a running motion while keeping your hips level.', 'cardio', ARRAY['core','hip_flexors','shoulders'], 'beginner', '[{"timestamp":0,"text":"Mountain climbers. Drive your knees in and keep your hips level.","type":"instruction"}]'::jsonb, false),
('Jumping Jacks', 'Stand with feet together, arms at sides. Jump feet out wide while raising arms overhead, then jump back to start.', 'cardio', ARRAY['full_body'], 'beginner', '[{"timestamp":0,"text":"Jumping jacks. Jump out and in, arms up and down.","type":"instruction"}]'::jsonb, false),
('High Knees', 'Run in place, driving your knees above hip height with each step. Pump your arms and maintain a quick pace.', 'cardio', ARRAY['hip_flexors','core','quads'], 'beginner', '[{"timestamp":0,"text":"High knees. Drive your knees up and pump your arms.","type":"instruction"}]'::jsonb, false),
('Battle Ropes', 'Hold one rope end in each hand. Create alternating waves by rapidly raising and lowering your arms while staying in an athletic stance.', 'cardio', ARRAY['shoulders','core','back'], 'intermediate', '[{"timestamp":0,"text":"Battle ropes. Alternate your arms and keep the waves going.","type":"instruction"}]'::jsonb, false),
('Rowing Machine', 'Sit on the rower, grip the handle. Drive with your legs first, then lean back slightly and pull the handle to your chest. Reverse the motion to return.', 'cardio', ARRAY['back','quads','core','biceps'], 'beginner', '[{"timestamp":0,"text":"Rowing. Legs push first, then lean back and pull.","type":"instruction"}]'::jsonb, false),

-- ═══ Mobility (8) ═══
('Downward Dog', 'From all fours, lift your hips up and back to form an inverted V. Press your heels toward the ground, straighten your arms, and lengthen your spine.', 'mobility', ARRAY['hamstrings','calves','shoulders','back'], 'beginner', '[{"timestamp":0,"text":"Downward dog. Press your heels down and lengthen your spine.","type":"instruction"}]'::jsonb, false),
('World''s Greatest Stretch', 'Lunge forward, place the same-side hand on the ground, rotate your opposite arm to the sky. Feel the stretch through hip, thoracic spine, and hamstrings.', 'mobility', ARRAY['hip_flexors','hamstrings','back','core'], 'beginner', '[{"timestamp":0,"text":"World''s greatest stretch. Lunge deep and rotate to open your chest.","type":"instruction"}]'::jsonb, false),
('Cat-Cow', 'On hands and knees, alternate between arching your back and rounding it. Inhale as you drop your belly and look up, exhale as you round and tuck your chin.', 'mobility', ARRAY['back','core','neck'], 'beginner', '[{"timestamp":0,"text":"Cat-cow. Arch your back on the inhale, round on the exhale.","type":"instruction"}]'::jsonb, false),
('90/90 Hip Stretch', 'Sit with one leg in front at 90 degrees and the other behind at 90 degrees. Lean your chest over the front shin to deepen the stretch.', 'mobility', ARRAY['hip_flexors','glutes'], 'beginner', '[{"timestamp":0,"text":"Ninety-ninety hip stretch. Lean forward over your front shin.","type":"instruction"}]'::jsonb, false),
('Thoracic Spine Rotation', 'Lie on your side with knees stacked and bent. Open your top arm across your body, rotating your upper back while keeping knees together.', 'mobility', ARRAY['back','core'], 'beginner', '[{"timestamp":0,"text":"Thoracic rotation. Open your arm across and rotate through your upper back.","type":"instruction"}]'::jsonb, false),
('Ankle Circles', 'Lift one foot off the ground and slowly rotate your ankle in large circles. Do both directions, then switch feet.', 'mobility', ARRAY['calves'], 'beginner', '[{"timestamp":0,"text":"Ankle circles. Slow, controlled circles in each direction.","type":"instruction"}]'::jsonb, false),
('Shoulder Pass-Through', 'Hold a band or dowel with a wide grip. Keeping arms straight, slowly raise it overhead and behind your back, then return.', 'mobility', ARRAY['shoulders','chest'], 'beginner', '[{"timestamp":0,"text":"Shoulder pass-throughs. Arms straight, take the band overhead and behind.","type":"instruction"}]'::jsonb, false),
('Couch Stretch', 'Kneel with one foot on the ground and the other knee against a wall behind you, shin vertical. Squeeze your glutes and push your hips forward.', 'mobility', ARRAY['hip_flexors','quads'], 'intermediate', '[{"timestamp":0,"text":"Couch stretch. Push your hips forward and squeeze your glutes.","type":"instruction"}]'::jsonb, false),

-- ═══ Fascia (5) ═══
('Foam Roll — IT Band', 'Lie on your side with a foam roller under your outer thigh. Roll slowly from hip to just above the knee, pausing on tender spots for 20-30 seconds.', 'fascia', ARRAY['quads','hip_flexors'], 'beginner', '[{"timestamp":0,"text":"IT band roll. Move slowly and pause on tender spots.","type":"instruction"}]'::jsonb, false),
('Foam Roll — Thoracic Spine', 'Lie face-up with a foam roller under your upper back. Cross arms over chest and slowly roll from mid-back to upper back.', 'fascia', ARRAY['back'], 'beginner', '[{"timestamp":0,"text":"Thoracic foam roll. Roll slowly through your upper back.","type":"instruction"}]'::jsonb, false),
('Foam Roll — Quads', 'Lie face-down with a foam roller under your thighs. Roll from hip to just above the knee, turning slightly to hit inner and outer quad.', 'fascia', ARRAY['quads'], 'beginner', '[{"timestamp":0,"text":"Quad foam roll. Roll from hip to knee, pausing on tight spots.","type":"instruction"}]'::jsonb, false),
('Lacrosse Ball — Glutes', 'Sit on a lacrosse ball positioned under one glute. Roll slowly in small circles, finding trigger points. Apply sustained pressure on tender areas.', 'fascia', ARRAY['glutes'], 'beginner', '[{"timestamp":0,"text":"Glute release with lacrosse ball. Find the tight spots and breathe into them.","type":"instruction"}]'::jsonb, false),
('Foam Roll — Calves', 'Sit with a foam roller under your calves. Cross one leg over the other for added pressure and roll from ankle to just below the knee.', 'fascia', ARRAY['calves'], 'beginner', '[{"timestamp":0,"text":"Calf foam roll. Roll slowly from ankle to knee.","type":"instruction"}]'::jsonb, false),

-- ═══ Recovery (5) ═══
('Child''s Pose', 'Kneel and sit back on your heels, arms extended forward on the ground. Let your forehead rest on the floor and breathe deeply into your back.', 'recovery', ARRAY['back','shoulders','hip_flexors'], 'beginner', '[{"timestamp":0,"text":"Child''s pose. Relax into the stretch and breathe deeply.","type":"instruction"}]'::jsonb, false),
('Supine Spinal Twist', 'Lie on your back, pull one knee across your body while keeping shoulders on the ground. Look toward the opposite hand and hold.', 'recovery', ARRAY['back','core','glutes'], 'beginner', '[{"timestamp":0,"text":"Spinal twist. Let gravity pull your knee down and relax.","type":"instruction"}]'::jsonb, false),
('Legs Up the Wall', 'Lie on your back with legs extended straight up a wall. Let your arms rest at your sides and focus on deep, slow breathing.', 'recovery', ARRAY['hamstrings','calves'], 'beginner', '[{"timestamp":0,"text":"Legs up the wall. Relax completely and breathe slowly.","type":"instruction"}]'::jsonb, false),
('Pigeon Pose', 'From a plank, bring one knee forward behind your wrist. Extend the other leg behind you. Lower your chest toward the ground for a deep hip stretch.', 'recovery', ARRAY['glutes','hip_flexors'], 'beginner', '[{"timestamp":0,"text":"Pigeon pose. Sink into the stretch and let your hips open.","type":"instruction"}]'::jsonb, false),
('Diaphragmatic Breathing', 'Lie on your back with knees bent. Place one hand on your chest, one on your belly. Breathe deeply so only your belly rises. Exhale slowly.', 'recovery', ARRAY['core'], 'beginner', '[{"timestamp":0,"text":"Belly breathing. Inhale through your nose, fill your belly, exhale slowly.","type":"instruction"}]'::jsonb, false),

-- ═══ Flexibility (5) ═══
('Standing Hamstring Stretch', 'Stand and place one heel on an elevated surface. Keep your leg straight and hinge forward at the hips until you feel a stretch behind your thigh.', 'flexibility', ARRAY['hamstrings'], 'beginner', '[{"timestamp":0,"text":"Hamstring stretch. Hinge forward with a flat back.","type":"instruction"}]'::jsonb, false),
('Seated Forward Fold', 'Sit with legs extended in front. Reach for your toes, hinging at the hips with a flat back. Hold and breathe into the stretch.', 'flexibility', ARRAY['hamstrings','back'], 'beginner', '[{"timestamp":0,"text":"Forward fold. Reach for your toes and breathe into the stretch.","type":"instruction"}]'::jsonb, false),
('Doorway Chest Stretch', 'Stand in a doorway with forearms on the frame at 90 degrees. Step one foot forward and lean in until you feel a stretch across your chest.', 'flexibility', ARRAY['chest','shoulders'], 'beginner', '[{"timestamp":0,"text":"Chest stretch. Lean forward through the doorway and open your chest.","type":"instruction"}]'::jsonb, false),
('Figure Four Stretch', 'Lie on your back, cross one ankle over the opposite knee. Pull the bottom leg toward your chest until you feel a deep stretch in the crossed-leg glute.', 'flexibility', ARRAY['glutes','hip_flexors'], 'beginner', '[{"timestamp":0,"text":"Figure four stretch. Pull your knee in and feel the stretch in your glute.","type":"instruction"}]'::jsonb, false),
('Neck Stretches', 'Gently tilt your head to one side, bringing your ear toward your shoulder. Hold, then switch sides. Follow with chin tucks and gentle rotations.', 'flexibility', ARRAY['neck'], 'beginner', '[{"timestamp":0,"text":"Neck stretches. Tilt gently and hold. No forcing.","type":"instruction"}]'::jsonb, false),

-- ═══ Balance (4) ═══
('Single-Leg Balance', 'Stand on one foot with a slight knee bend. Hold your arms out for balance. Focus on a fixed point ahead. Progress by closing your eyes.', 'balance', ARRAY['calves','core','quads'], 'beginner', '[{"timestamp":0,"text":"Single-leg balance. Stand tall, engage your core, find a focal point.","type":"instruction"}]'::jsonb, false),
('BOSU Ball Squat', 'Stand on a BOSU ball dome-side up. Perform a squat while maintaining balance. Keep your core tight and arms out front for counterbalance.', 'balance', ARRAY['quads','glutes','core'], 'intermediate', '[{"timestamp":0,"text":"BOSU ball squats. Squat down with control and keep your balance.","type":"instruction"}]'::jsonb, false),
('Warrior III', 'Stand on one leg, hinge forward at the hips and extend your back leg behind you. Arms reach forward. Body forms a T shape.', 'balance', ARRAY['hamstrings','glutes','core','shoulders'], 'intermediate', '[{"timestamp":0,"text":"Warrior three. Hinge forward and extend into a T shape.","type":"instruction"}]'::jsonb, false),
('Bird Dog', 'On hands and knees, extend one arm forward and the opposite leg back simultaneously. Hold briefly, then switch sides. Keep hips level.', 'balance', ARRAY['core','back','glutes'], 'beginner', '[{"timestamp":0,"text":"Bird dog. Extend opposite arm and leg, keep your hips level.","type":"instruction"}]'::jsonb, false);
